### ISSUE TITLE
LS19

### ISSUE THREAD

**Issue by dtmaster79** [Donkie/I3DShapesTool#1]
Hi,

can you please update this tools for farming simulator 19?

Thx

**Comment by Donkie** [comment]
I wish, but they changed the encryption in FS17 and forward. Was such a long time ago since I made this that I've forgotten how to crack it.

I'll update you if there comes a time when it supports FS17 and FS19.

**Comment by ziemniak02** [comment]
Hi,
How Can I use this tool ?

**Comment by iamchriswick** [comment]
Second that! How do we use this tool?

**Comment by Donkie** [comment]
Sorry for not including any proper Readme.

You can download a built version in the Releases section. Extract it somewhere then open cmd in the same directory, type in the name of the exe to get further instructions.

I will improve these instructions later tonight when I have more time.

**Comment by ziemniak02** [comment]
HI,
Could you write a step-by-step instruction?

**Comment by Donkie** [comment]
I've updated the readme, see if that helps @ziemniak02 @iamchriswick

**Comment by ziemniak02** [comment]
I don't know if I'm doing something wrong, but when I type anything, the tool turns off.

**Comment by ziemniak02** [comment]
Thanks, I have two  questions, have you worked on solution to FS19 or have you idea how to open shapes file with notepad ?

**Comment by Donkie** [comment]
I have been working on it but I have to redo all the reverse engineering from scratch.

You can't use notepad to open the shapes file, it's compressed and encrypted

**Comment by ziemniak02** [comment]
Have someone idea how to fix FS19 shapes file ?

**Comment by Donkie** [comment]
@dtmaster79 @ziemniak02 @iamchriswick Check the latest release, FS17 and FS19 support is here!
