### ISSUE TITLE
File version 5?

### ISSUE THREAD

**Issue by kbrandwijk** [Donkie/I3DShapesTool#11]
Tried to dump a shapes file. File version 5, Unsupported version. Any plans of supporting this version?

**Comment by Donkie** [comment]
What game is the file from?

**Comment by kbrandwijk** [comment]
FS19

**Comment by kbrandwijk** [comment]
Any feedback on this?

**Comment by Donkie** [comment]
Sorry, I've been very busy lately, I will look at it when I have time.

**Comment by kbrandwijk** [comment]
Thanks!

**Comment by Donkie** [comment]
Is the file included in the game, and if so, what is the path?

**Comment by daytonadam** [comment]
hi! have the same problem, is a  FS19 dlc, any help?

**Comment by kbrandwijk** [comment]
@Donkie Basically any .i3d.shapes file that is part of a DLC, yes.

**Comment by Donkie** [comment]
I don't own any DLC so I can't really test that I'm afraid.

**Comment by KITT3000** [comment]
In DLC, shapes are encrypted, but it's a simple cipher based on Caesar's cipher.

**Comment by Donkie** [comment]
This program already decrypts shape files, but I've never encountered file version 5 before so I cannot verify that the program will work for them or not.

**Comment by KITT3000** [comment]
These files are of the same version as the others from the game, only the first part of the file is encrypted (blocks 01, 02 and 03 are changed, I am writing about HEX coding here). Until they are decoded, they will not load these files even Giants Editor (i3d file editor provided by the developers).

**Comment by Vanquish081** [comment]
> 
> 
> These files are of the same version as the others from the game, only the first part of the file is encrypted (blocks 01, 02 and 03 are changed, I am writing about HEX coding here). Until they are decoded, they will not load these files even Giants Editor (i3d file editor provided by the developers).

could you extract it?

@Donkie here an example file V5
https://drive.google.com/file/d/16mL2Pdv1hf5HUD3P-hhK0FFnnShdLEXN/view?usp=sharing

**Comment by Donkie** [comment]
Thank you @Vanquish081
I will check it out.

**Comment by Donkie** [comment]
I have pushed a new update https://github.com/Donkie/I3DShapesTool/releases/tag/v1.2.0

These files that were broken has a encrypted seed as @KITT3000 mentioned. Since the seed can only be a number between 0 and 255, I simply made the program try every seed until it finds one that doesn't produce garbage output.

See if the program now works as desired. If you have any files that still does not want to work, please send them to me and I will take a look.

**Comment by Vanquish081** [comment]
@Donkie  Thank you, work very fine for explore this files.

P.D.: Do you know if is possible load i3d from DLC with a xml?

**Comment by Donkie** [comment]
Ah I didn't consider the uvmaps as well. I can take a look at them. Scaling is more difficult to deal with.

This tool does not consider the i3d xmls at all, it is only for decoding the shapes files (currently)

**Comment by KITT3000** [comment]
> P.D.: Do you know if is possible load i3d from DLC with a xml?
Wdym? GE will load i3d after decoding the shapes, XML files are not blocked in any way.

**Comment by Vanquish081** [comment]
> 
> 
> > P.D.: Do you know if is possible load i3d from DLC with a xml?
> 
> Wdym? GE will load i3d after decoding the shapes, XML files are not blocked in any way.

Is for modifie datas but loading the same i3d of DLC.

**Comment by KITT3000** [comment]
@Vanquish081 No, there is no such possibility, the game loads i3d from the place where modDesc was called, but you can still refer to the main game folder, the DLC folder cannot do without script.

**Comment by Vanquish081** [comment]
Ok, I would have liked to put wheels on the 9RX instead of crawlers, now extracting the obj was easier see the position for the wheels, but if I can not charge the vehicle from no use dlc....

**Comment by daytonadam** [comment]
someone can put an example of how to do it? i do it in march with the old version and now not remember how do this

**Comment by Vanquish081** [comment]
> 
> 
> someone can put an example of how to do it? i do it in march with the old version and now not remember how do this

Simply drag and drop th3 i3d.shapes file to I3DShapesTool.exe

**Comment by Melegari** [comment]
Hello After the process, I now have all the 3D objects individually, as shown in the image, 
![3d](https://user-images.githubusercontent.com/67880202/86544131-483a6f00-bf1c-11ea-9039-5649aa62c408.png)
 what should I do now? Thank you

**Comment by Vanquish081** [comment]
> 
> 
> Hello After the process, I now have all the 3D objects individually, as shown in the image,
> what should I do now? Thank you

You can import to prefer software 3D for use this parts for example.

**Comment by BoerWes** [comment]
> > Hello After the process, I now have all the 3D objects individually, as shown in the image,
> > what should I do now? Thank you
> 
> You can import to prefer software 3D for use this parts for example.

Can this program make the .shapes file stay intact? Or can it only export it to .obj?

**Comment by Donkie** [comment]
@BoerWes It only exports to obj at the moment.

**Comment by frontloda28** [comment]
> Since the seed can only be a number between 0 and 255, I simply made the program try every seed until it finds one that doesn't produce garbage output.
Wouldn't it possible to show the values that seem to work and edit the .shapes by hand in a hex editor according to those numbers? My hex knowledge is quite small, so it might be more complicated than I think.

**Comment by Donkie** [comment]
Latest release should support all files up to and including FS22 now. Please make a new ticket if something doesn't work.
