### ISSUE TITLE
One way process?

### ISSUE THREAD

**Issue by kbrandwijk** [Donkie/I3DShapesTool#12]
Is extracting the binary data a one way process, or could one use the same bits and pieces from the codebase to make it go the other way to (i3d -> binary shapes file)?

**Comment by Donkie** [comment]
Technically it should be 100% possible to convert it back into an identical binary shapes file, but this tool does not support it at all currently.

**Comment by VirRus77** [comment]
Since the binary format is not fully open, it cannot be converted back to binary.

**Comment by Donkie** [comment]
Moved to #24
