### ISSUE TITLE
Export to FBX

### ISSUE THREAD

**Issue by KITT3000** [Donkie/I3DShapesTool#15]
Is there any FBX support planned? My main goal is not to lose information about bones animation and vertex color and keep the structure of scenography.

**Comment by Donkie** [comment]
FBX is tricky to work with since it's proprietary, there are no big good libraries out there that can help me with the export. There are some though, and I might look into that. Can't promise anything though.

**Comment by MirceaPrunaru** [comment]
you

> FBX is tricky to work with since it's proprietary, there are no big good libraries out there that can help me with the export. There are some though, and I might look into that. Can't promise anything though.

you can take a look at collada .dae from what i know is free

**Comment by Donkie** [comment]
Moved to these tasks #20 #22
