### ISSUE TITLE
Position/Rotation XYZ

### ISSUE THREAD

**Issue by Alan207** [Donkie/I3DShapesTool#19]
Hello great tool, now also works with FS22 :) but, it would be useful to change something namely, when I export a model directly from Giants Editor to obj format, then after importing e.g. to Blender the model is in the same position as in Giants Editor (only center of rotation and rotation is reset which is obvious), but when I export a model with your tool the model changes position to 0,0,0 instead of only resetting center of rotation and rotation. Is it possible to change this?

![export_GE](https://user-images.githubusercontent.com/62470910/146068513-1cd559c1-77b3-43e1-8df9-0c79ec477cd0.png)
![export_I3DST](https://user-images.githubusercontent.com/62470910/146069652-bc75efef-3699-4fab-a4ae-d29bd3d318ba.png)

**Comment by Donkie** [comment]
Yeah this is something I've struggled with too. Afaik this rotational information is stored in the .i3d file and not the .i3d.shapes, right?

**Comment by Alan207** [comment]
Yes that's right, this information is included in the .i3d

**Comment by Donkie** [comment]
This is fixed, please try it out in the new release!

**Comment by Alan207** [comment]
And with medium and larger shapes files (using i3d parsing) some elements are scattered

![import_preview](https://user-images.githubusercontent.com/62470910/146689844-6cf728b5-1f80-4400-8932-b8b14ea6ed81.png)

**Comment by Donkie** [comment]
What model are you trying to export?
Can you show a print of the console when exporting?

**Comment by Alan207** [comment]
Here is a sample model series8S.i3d 

![cmd_00](https://user-images.githubusercontent.com/62470910/146806245-07d0c5e9-a947-45c3-8870-aa89dbb2cf78.PNG)

[series8S.zip](https://github.com/Donkie/I3DShapesTool/files/7746929/series8S.zip)

**Comment by Alan207** [comment]
I think the problem is that the coordinates in the i3d file contain "e-" and thus the model is scattered 🤔

![xml_view](https://user-images.githubusercontent.com/62470910/146993154-97113c6b-ad05-4acb-b1a9-1b7e995e3658.png)

**Comment by Donkie** [comment]
Weird, this works fine for me.
Old behaviour:
![image](https://user-images.githubusercontent.com/2332094/147860849-32e89f1c-eff8-40dc-b5b0-fb4812d8672a.png)

New behaviour:
![image](https://user-images.githubusercontent.com/2332094/147860851-055a7dbe-31f7-435f-ac98-8906a7d8fa8f.png)

series8S model.
Can you try with a different model? Are you sure you haven't modified the scene file or something like that?

**Comment by Alan207** [comment]
It's the same with other models, too. Check out this one, for example - chSeries

![untitled](https://user-images.githubusercontent.com/62470910/147975702-51df9938-8fd5-42bd-b525-2e792d4160ac.png)

[chSeries.zip](https://github.com/Donkie/I3DShapesTool/files/7803840/chSeries.zip)


.

**Comment by Donkie** [comment]
I think I found the issue! Try this build:
[I3DShapesTool.zip](https://github.com/Donkie/I3DShapesTool/files/7816921/I3DShapesTool.zip)

**Comment by Alan207** [comment]
Unfortunately, there continues to be a problem with this.

![untitled](https://user-images.githubusercontent.com/62470910/148274988-1a20872a-1f1a-4dee-82d5-1d6923760998.png)

![cmd_01](https://user-images.githubusercontent.com/62470910/148275011-17000df8-7ac4-401e-91ab-844693c80976.PNG)

**Comment by Alan207** [comment]
Are you working on a new update?

**Comment by Donkie** [comment]
Hi, sorry for the wait. I've been busy with some other stuff. I have not forgotten you and I will look into this soon.

**Comment by Donkie** [comment]
Sorry for the long wait but I think I got a fully working version now!
![image](https://user-images.githubusercontent.com/2332094/172072094-c1ba893c-bd86-4d78-8795-b1de7164ac28.png)
[I3DShapesTool.zip](https://github.com/Donkie/I3DShapesTool/files/8840835/I3DShapesTool.zip)
