### ISSUE TITLE
Position UV

### ISSUE THREAD

**Issue by Alan207** [Donkie/I3DShapesTool#26]
Hi after export the UV grid is in the wrong place. It should be in the place of the green square like in the picture.

![UV_preview](https://user-images.githubusercontent.com/62470910/146245778-b71d3003-705d-4bea-b345-0c1052dbd471.png)

**Comment by Donkie** [comment]
Has this always been a problem or did it appear just now?

Could you explain a bit more what UV grid means?

**Comment by Alan207** [comment]
The UV problem was there before, it's just that in previous versions of the program, after exporting, the UV mesh was stretched. Now it looks correct, it's just in the wrong position.

**Comment by Alan207** [comment]
The UV problem was there before, it's just that in previous versions of the program, after exporting, the UV mesh was stretched. Now it looks correct, it's just in the wrong position.

**Comment by Alan207** [comment]
The UV problem existed before, it's just that in previous versions of the program, when exported, the UV grid was stretched. Now it looks better, but not quite. In the picture is an example on the left is correctly as it should look and on the right you can see that it is stretched. 

![UV_viewer](https://user-images.githubusercontent.com/62470910/146268928-779fa653-4a48-4836-98d0-003d4050ebf9.png)

**Comment by Donkie** [comment]
[I3DShapesTool.zip](https://github.com/Donkie/I3DShapesTool/files/7730062/I3DShapesTool.zip)
Try this exe, see if it fixes your issues

**Comment by Alan207** [comment]
It didn't help.

**Comment by Alan207** [comment]
The UV position is now correct, but the mesh still doesn't look right (it's still like what's in the picture in the comment above).

**Comment by Alan207** [comment]
![tire_viewer](https://user-images.githubusercontent.com/62470910/146611423-c6a207ca-26b4-4f5c-9d9c-b8cebd31f4c9.png)

**Comment by Donkie** [comment]
funky, looking into it

**Comment by Donkie** [comment]
I think I found the issue, UV coordinates were only written with 2 decimals so a lot of precision was lost. Try this build:
[I3DShapesTool-fix2.zip](https://github.com/Donkie/I3DShapesTool/files/7738975/I3DShapesTool-fix2.zip)

**Comment by Alan207** [comment]
Yes, now UV is exporting correctly 👍

**Comment by Donkie** [comment]
Great!
