### ISSUE TITLE
Failed to load part

### ISSUE THREAD

**Issue by Alan207** [Donkie/I3DShapesTool#27]
When exporting larger shapes files that have more elements, a message like the one in the picture appears and all parts of the shapes file are not exported to either obj or bin.

![export_bug](https://user-images.githubusercontent.com/62470910/146651199-ffc0152e-ad71-47d5-95be-d5afaf9403ae.PNG)

**Comment by Donkie** [comment]
Thanks, will look into it

**Comment by Donkie** [comment]
[I3DShapesTool-fix3.zip](https://github.com/Donkie/I3DShapesTool/files/7739932/I3DShapesTool-fix3.zip)

See if this build works for you

**Comment by Alan207** [comment]
Now it works properly 👍
