### ISSUE TITLE
Exporting items with the same name

### ISSUE THREAD

**Issue by Alan207** [Donkie/I3DShapesTool#28]
When exporting items with the same names, only one item is exported instead of, for example, four items.

![scenegraph](https://user-images.githubusercontent.com/62470910/146656648-a8c4df94-e394-47cf-a570-fed46dbbef90.PNG)

**Comment by Donkie** [comment]
I imagine this will be better when I add the I3D xml parsing. The shape names listed in that will be used in the export then instead.

**Comment by Alan207** [comment]
This seems to be a better solution, but we will see how it will be in practice.

**Comment by Donkie** [comment]
Published a new release, try it out and see if it fixes this

**Comment by Alan207** [comment]
Unfortunately, it continues the same way.

**Comment by Alan207** [comment]
And with medium and larger shapes files (using i3d parsing) some elements are scattered

![import_preview](https://user-images.githubusercontent.com/62470910/146689703-7fbefdc3-b2c0-4777-843f-4d0b3be55638.png)
.

**Comment by Donkie** [comment]
Do you have the corresponding .i3d and .i3d.shapes files in the same folder?

**Comment by Alan207** [comment]
Yes

**Comment by Donkie** [comment]
[I3DShapesTool.zip](https://github.com/Donkie/I3DShapesTool/files/7798268/I3DShapesTool.zip)
I think I found the issue. Try this build. Output files will now be named such as: "<name>_<id>.obj", to make sure the name is always unique.

**Comment by Alan207** [comment]
Great, now it is correct  :+1:
