### ISSUE TITLE
Latest release doesn't export bin files

### ISSUE THREAD

**Issue by kbrandwijk** [Donkie/I3DShapesTool#29]
The option -b stopped working in the latest release. I run the exact same command with 1.3.0, and it exports the bin files.

**Comment by Donkie** [comment]
Can't reproduce, can you show me the full command?

**Comment by kbrandwijk** [comment]
![image](https://user-images.githubusercontent.com/852069/172133507-a70b10a1-a8a9-4cc7-b849-916f44f3b684.png)

Done with a very simple test file with a single cube, created in GE.
[cube.zip](https://github.com/Donkie/I3DShapesTool/files/8843299/cube.zip)

**Comment by Donkie** [comment]
Ah, I've already fixed it a while ago and I tested a newer version. Will push a release soon!

**Comment by Donkie** [comment]
https://github.com/Donkie/I3DShapesTool/releases/tag/v1.5.0 Pushed a release now!

**Comment by kbrandwijk** [comment]
Much appreciated! Great as always!
![image](https://user-images.githubusercontent.com/852069/172173444-6b5f28ef-777f-404e-8698-772081ddd7cf.png)
