### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by 2fast4yooou** [Donkie/I3DShapesTool#3]
Hey mate, 
I don't know if you are still continuing this project, but I may have something for you, that could help...
Is there a way to contact you personal?

**Comment by Donkie** [comment]
I actually have it mostly sorted out already, the file format hasn't changed as much as I thought from FS15 to FS17, so I have successfully decrypted it. However, I'm having some issues converting it from binary to .obj at the moment, which is what I'm working on.

**Comment by 2fast4yooou** [comment]
That are great news! :D 
But tbh I was more thinking about FS19.. since that is the lastest version of the series...
There is a mod, a Xerion 5000 with crawler tracks base of the Xerion from the Platinum Addon... And you are able to open the i3D files ins GE.. so that might help you while reverse engineering.

**Comment by Donkie** [comment]
I think FS17 and FS19 uses same format so don't worry

**Comment by Donkie** [comment]
@2fast4yooou  Check the latest release, FS17 and FS19 support is here!
