### ISSUE TITLE
I3dShapesTool Not Working 

### ISSUE THREAD

**Issue by zocker133** [Donkie/I3DShapesTool#34]
I unpacked the ZIP and started cmd in the folder and I executed I3dShapesTool -h with enter and the file is closed. Ask for help

**Comment by Donkie** [comment]
What version of Windows are you running?

Try downloading and installing the .NET Desktop Runtime on this page https://dotnet.microsoft.com/en-us/download/dotnet/3.1 and see if it helps

**Comment by zocker133** [comment]
Hello thank you for your Message I just installed dotnet and again I3DShapesTool -h tries to run still does not work he says he could not find command. I have windows 10 64bit

**Comment by Donkie** [comment]
Could you show a screenshot of the cmd after you have tried executing the command?

**Comment by Donkie** [comment]
Ah. Download the .exe file instead of the .zip from the release page. The .zip only contains the source code and not the program itself!

**Comment by zocker133** [comment]
ok but as soon as I enter here I3DShapesTool -h and press enter cmd is finished and nothing happens more

![grafik](https://user-images.githubusercontent.com/109063396/178312418-54677b2f-1382-444e-901e-d343f49417b2.png)


here he also shows me which errors

![grafik](https://user-images.githubusercontent.com/109063396/178312221-3e0f2f78-ada3-484b-98f8-d3bfef6a08f1.png)

![grafik](https://user-images.githubusercontent.com/109063396/178312286-3a83e971-abcf-4d82-8a3d-88030c6dc619.png)

**Comment by Donkie** [comment]
you should get the full help screen anytime you do something wrong, don't you see it?
![image](https://user-images.githubusercontent.com/2332094/178314580-e09b13d6-889b-427d-aea8-1cd68096872c.png)

**Comment by zocker133** [comment]
as soon as I run the exe the program looks like this
![grafik](https://user-images.githubusercontent.com/109063396/178320818-c6134502-a1bd-4668-b68b-c4f54ef57623.png)
!
[grafik](https://user-images.githubusercontent.com/109063396/178320883-d50b7687-b95e-4c5f-8f1b-42ae85298587.png)

**Comment by Donkie** [comment]
yes, that is how it's supposed to look like. There is no GUI or anything like that, follow the help text that is written.

**Comment by zocker133** [comment]
OK Thank you
