### ISSUE TITLE
Ubuntu 22.04 / .NET6 support

### ISSUE THREAD

**Issue by thraidh** [Donkie/I3DShapesTool#35]
Currently the application does not work on Ubuntu 22.04, because it only supports .NET 6. 
I tried replacing all instances of `netcoreapp3.1` in `.csproj` files with `net6.0` and that works for me, but I don't know what would break, so I would not dare making a PR for that.
From how I understand the Microsoft documentation it should be possible to provide multiple target frameworks.

**Comment by Donkie** [comment]
Thanks, I will look into targeting more platforms!

**Comment by thraidh** [comment]
I'm about to start working on #23, but it would make it easier for me, if `net6.0` was there.

**Comment by Donkie** [comment]
I've switched the app to .NET 6 now!

**Comment by thraidh** [comment]
`I3DShapesToolTest/I3DShapesToolTest.csproj` still contains `netcoreapp3.1`.

**Comment by Donkie** [comment]
Ah of course, updated that as well now!

**Comment by thraidh** [comment]
Thanks! Works now.
